--------------------------------------------------------
--  File created - Tuesday-August-04-2020   
--------------------------------------------------------
DROP TABLE "LOFO"."USERS";
DROP TABLE "LOFO"."FOUNDITEM";
DROP TABLE "LOFO"."LOSTITEM";
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "LOFO"."USERS" 
   (	"USERPASSWORD" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"USERNOPHONE" VARCHAR2(20 BYTE), 
	"USEREMAIL" VARCHAR2(100 BYTE), 
	"USERROLE" VARCHAR2(20 BYTE), 
	"USERSTATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOUNDITEM
--------------------------------------------------------

  CREATE TABLE "LOFO"."FOUNDITEM" 
   (	"FITEMID" VARCHAR2(500 BYTE), 
	"USEREMAIL" VARCHAR2(500 BYTE), 
	"FITEMNAME" VARCHAR2(500 BYTE), 
	"FITEMCATEGORY" VARCHAR2(100 BYTE), 
	"FITEMDATE" VARCHAR2(20 BYTE), 
	"FITEMTIME" VARCHAR2(20 BYTE), 
	"FITEMLOCATION" VARCHAR2(100 BYTE), 
	"FITEMDESCRIPTION" VARCHAR2(500 BYTE), 
	"FITEMPHOTO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FITEMPHOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table LOSTITEM
--------------------------------------------------------

  CREATE TABLE "LOFO"."LOSTITEM" 
   (	"LITEMID" VARCHAR2(500 BYTE), 
	"USEREMAIL" VARCHAR2(500 BYTE), 
	"LITEMNAME" VARCHAR2(500 BYTE), 
	"LITEMCATEGORY" VARCHAR2(100 BYTE), 
	"LITEMDATE" VARCHAR2(20 BYTE), 
	"LITEMTIME" VARCHAR2(20 BYTE), 
	"LITEMLOCATION" VARCHAR2(100 BYTE), 
	"LITEMDESCRIPTION" VARCHAR2(500 BYTE), 
	"LITEMPHOTO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("LITEMPHOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into LOFO.USERS
SET DEFINE OFF;
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('202cb962ac59075b964b07152d234b70','Suraiya Anuar','01139388505','suraiya@gmail.com','User','Active');
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('698d51a19d8a121ce581499d7b701668','Aishah Ahmad','01139388505','aishah@gmail.com','User','Active');
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('202cb962ac59075b964b07152d234b70','User2 ','0111111111','user2@gmail.com','User','Active');
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('202cb962ac59075b964b07152d234b70','User 3','0122355544','user3@gmail.com','User','Active');
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('202cb962ac59075b964b07152d234b70','User 1','01111111111','user1@gmail.com','User','Active');
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('202cb962ac59075b964b07152d234b70','Admin','01139388505','admin3@gmail.com','Admin','Active');
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('202cb962ac59075b964b07152d234b70','Nurul Hidayah','015465454','dot@gmail.com','User','Active');
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('b59c67bf196a4758191e42f76670ceba','New User','01139388505','aaaa@gmail.com','User','Active');
Insert into LOFO.USERS (USERPASSWORD,USERNAME,USERNOPHONE,USEREMAIL,USERROLE,USERSTATUS) values ('202cb962ac59075b964b07152d234b70','Priskila Elvy','0114569887','priss@gmail.com','User','Active');
REM INSERTING into LOFO.FOUNDITEM
SET DEFINE OFF;
Insert into LOFO.FOUNDITEM (FITEMID,USEREMAIL,FITEMNAME,FITEMCATEGORY,FITEMDATE,FITEMTIME,FITEMLOCATION,FITEMDESCRIPTION) values ('146','priss@gmail.com','kad matrik Fahyu','UiTM Matrics Card','2020-07-08','10:31','Kolej Tun Gemala B','jumpa dekat tangga aras 3');
Insert into LOFO.FOUNDITEM (FITEMID,USEREMAIL,FITEMNAME,FITEMCATEGORY,FITEMDATE,FITEMTIME,FITEMLOCATION,FITEMDESCRIPTION) values ('127','suraiya@gmail.com','laptop dell hitam','Laptop','2017-02-13','06:42','Pusat Islam Surau','jumpa kat bahagian solat perempuan');
Insert into LOFO.FOUNDITEM (FITEMID,USEREMAIL,FITEMNAME,FITEMCATEGORY,FITEMDATE,FITEMTIME,FITEMLOCATION,FITEMDESCRIPTION) values ('144','aishah@gmail.com','kunci kereta perodua','Keys','2020-04-30','02:41','Kolej Tun Lanang B',null);
Insert into LOFO.FOUNDITEM (FITEMID,USEREMAIL,FITEMNAME,FITEMCATEGORY,FITEMDATE,FITEMTIME,FITEMLOCATION,FITEMDESCRIPTION) values ('148','dot@gmail.com','kad bank maybank','Cards','2020-07-01','08:21','Cafe Kolej','jumpa dekat dengan ATM bank islam. mungkin tercicir. nak ambil sila contact saya. kad ada pada saya');
Insert into LOFO.FOUNDITEM (FITEMID,USEREMAIL,FITEMNAME,FITEMCATEGORY,FITEMDATE,FITEMTIME,FITEMLOCATION,FITEMDESCRIPTION) values ('147','dot@gmail.com','kad matrik Diana','UiTM Matrics Card','2020-07-05','08:19','Bilik Tutorial 1','jumpa bawah meja row 3 dari pintu belakang');
Insert into LOFO.FOUNDITEM (FITEMID,USEREMAIL,FITEMNAME,FITEMCATEGORY,FITEMDATE,FITEMTIME,FITEMLOCATION,FITEMDESCRIPTION) values ('145','aishah@gmail.com','laptop acer hitam','Laptop','2019-10-05','11:45','Bilik Tutorial 1','jumpa atas meja');
REM INSERTING into LOFO.LOSTITEM
SET DEFINE OFF;
Insert into LOFO.LOSTITEM (LITEMID,USEREMAIL,LITEMNAME,LITEMCATEGORY,LITEMDATE,LITEMTIME,LITEMLOCATION,LITEMDESCRIPTION) values ('63','suraiya@gmail.com','jam tangan','Other','2020-07-22','23:31','Kolej Tun Gemala B','cuba lagey');
Insert into LOFO.LOSTITEM (LITEMID,USEREMAIL,LITEMNAME,LITEMCATEGORY,LITEMDATE,LITEMTIME,LITEMLOCATION,LITEMDESCRIPTION) values ('64','priss@gmail.com','pendrive hitam Sandisk','Other','2020-07-10','11:16','Pusat Persatuan Pelajar','saya tertinggal pendrive macam ni kat PC kat kedai tanjung masa nak print. kalau jumpa sila contact saya');
--------------------------------------------------------
--  DDL for Index FOUNDITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOFO"."FOUNDITEM_PK" ON "LOFO"."FOUNDITEM" ("FITEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOSTITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOFO"."LOSTITEM_PK" ON "LOFO"."LOSTITEM" ("LITEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger FOUNDITEM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LOFO"."FOUNDITEM_TRG" 
BEFORE INSERT ON FOUNDITEM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LOFO"."FOUNDITEM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FOUNDITEM_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LOFO"."FOUNDITEM_TRG1" 
BEFORE INSERT ON FOUNDITEM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LOFO"."FOUNDITEM_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOSTITEM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LOFO"."LOSTITEM_TRG" 
BEFORE INSERT ON LOSTITEM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LOFO"."LOSTITEM_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table FOUNDITEM
--------------------------------------------------------

  ALTER TABLE "LOFO"."FOUNDITEM" ADD CONSTRAINT "FOUNDITEM_PK" PRIMARY KEY ("FITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LOFO"."FOUNDITEM" MODIFY ("FITEMID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOSTITEM
--------------------------------------------------------

  ALTER TABLE "LOFO"."LOSTITEM" ADD CONSTRAINT "LOSTITEM_PK" PRIMARY KEY ("LITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LOFO"."LOSTITEM" MODIFY ("LITEMID" NOT NULL ENABLE);
